import { Job } from "./types";

export const mockJobs: Job[] = [
  {
    id: "JOB-1001",
    productName: "Steel Bracket A2",
    customer: "Vantage Industries",
    quantity: 500,
    dueDate: "2026-09-20",
    status: "In Progress",
    assignedMachine: "CNC Mill 3",
    notes: "Customer requested tighter tolerance on mounting holes.",
  },
  {
    id: "JOB-1002",
    productName: "Aluminum Housing V3",
    customer: "Reyna Auto Parts",
    quantity: 1200,
    dueDate: "2026-09-19",
    status: "Delayed",
    assignedMachine: "Injection Molder 1",
    notes: "Waiting on raw material delivery, ETA pushed by 2 days.",
  },
  {
    id: "JOB-1003",
    productName: "Gear Shaft 45mm",
    customer: "Torque Systems",
    quantity: 300,
    dueDate: "2026-09-25",
    status: "Pending",
    assignedMachine: "Lathe 2",
  },
  {
    id: "JOB-1004",
    productName: "Circuit Panel B",
    customer: "Nexon Electronics",
    quantity: 800,
    dueDate: "2026-09-18",
    status: "Completed",
    assignedMachine: "Assembly Line 4",
  },
  {
    id: "JOB-1005",
    productName: "Hydraulic Valve Body",
    customer: "Vantage Industries",
    quantity: 150,
    dueDate: "2026-09-22",
    status: "In Progress",
    assignedMachine: "CNC Mill 1",
    notes: "Second inspection pass scheduled before shipping.",
  },
  {
    id: "JOB-1006",
    productName: "Plastic Casing C1",
    customer: "Orbit Devices",
    quantity: 2000,
    dueDate: "2026-09-18",
    status: "Delayed",
    assignedMachine: "Injection Molder 2",
    notes: "Mold defect found, tooling team notified.",
  },
  {
    id: "JOB-1007",
    productName: "Sensor Bracket Mini",
    customer: "Nexon Electronics",
    quantity: 600,
    dueDate: "2026-09-30",
    status: "Pending",
    assignedMachine: "CNC Mill 3",
  },
  {
    id: "JOB-1008",
    productName: "Motor Coupling Set",
    customer: "Torque Systems",
    quantity: 400,
    dueDate: "2026-09-17",
    status: "Completed",
    assignedMachine: "Lathe 1",
  },
];